const TLA: Record<string, string> = {
  // CONCACAF
  "United States": "USA", "USA": "USA",
  "Mexico": "MEX",
  "Canada": "CAN",
  "Panama": "PAN",
  "Costa Rica": "CRC",
  "Honduras": "HON",
  "Jamaica": "JAM",
  "El Salvador": "SLV",
  "Trinidad and Tobago": "TTO",
  "Cuba": "CUB",
  "Curaçao": "CUW", "Curacao": "CUW",
  "Haiti": "HAI",

  // CONMEBOL
  "Brazil": "BRA",
  "Argentina": "ARG",
  "Colombia": "COL",
  "Uruguay": "URU",
  "Ecuador": "ECU",
  "Paraguay": "PAR",
  "Bolivia": "BOL",
  "Chile": "CHI",
  "Peru": "PER",
  "Venezuela": "VEN",

  // UEFA
  "Germany": "GER",
  "France": "FRA",
  "Spain": "ESP",
  "Portugal": "POR",
  "England": "ENG",
  "Netherlands": "NED",
  "Italy": "ITA",
  "Belgium": "BEL",
  "Croatia": "CRO",
  "Switzerland": "SUI",
  "Serbia": "SRB",
  "Turkey": "TUR", "Türkiye": "TUR",
  "Austria": "AUT",
  "Scotland": "SCO",
  "Czechia": "CZE", "Czech Republic": "CZE",
  "Slovakia": "SVK",
  "Poland": "POL",
  "Hungary": "HUN",
  "Denmark": "DEN",
  "Wales": "WAL",
  "Ukraine": "UKR",
  "Greece": "GRE",
  "Romania": "ROU",
  "Slovenia": "SVN",
  "Albania": "ALB",
  "Iceland": "ISL",
  "Norway": "NOR",
  "Sweden": "SWE",
  "Finland": "FIN",
  "Republic of Ireland": "IRL", "Ireland": "IRL",
  "Northern Ireland": "NIR",
  "Georgia": "GEO",
  "Kosovo": "KVX",
  "Bosnia and Herzegovina": "BIH", "Bosnia & Herzegovina": "BIH", "Bosnia-Herzegovina": "BIH", "Bosnia": "BIH",
  "North Macedonia": "MKD",
  "Bulgaria": "BUL",
  "Montenegro": "MNE",
  "Israel": "ISR",
  "Armenia": "ARM",
  "Azerbaijan": "AZE",
  "Luxembourg": "LUX",
  "Belarus": "BLR",
  "Moldova": "MDA",
  "Lithuania": "LTU",
  "Latvia": "LVA",
  "Estonia": "EST",
  "Malta": "MLT",
  "Cyprus": "CYP",
  "Kazakhstan": "KAZ",
  "Andorra": "AND",
  "Faroe Islands": "FRO",
  "Gibraltar": "GIB",
  "Liechtenstein": "LIE",
  "San Marino": "SMR",

  // CAF
  "Morocco": "MAR",
  "Senegal": "SEN",
  "Egypt": "EGY",
  "Nigeria": "NGA",
  "Cameroon": "CMR",
  "Ghana": "GHA",
  "Ivory Coast": "CIV", "Côte d'Ivoire": "CIV", "Cote d'Ivoire": "CIV",
  "Algeria": "ALG",
  "Tunisia": "TUN",
  "DR Congo": "COD", "Congo DR": "COD", "Democratic Republic of the Congo": "COD",
  "Benin": "BEN",
  "Comoros": "COM",
  "South Africa": "RSA",
  "Mali": "MLI",
  "Zambia": "ZAM",
  "Guinea": "GUI",
  "Cape Verde": "CPV", "Cabo Verde": "CPV",
  "Tanzania": "TAN",
  "Uganda": "UGA",
  "Mozambique": "MOZ",
  "Rwanda": "RWA",
  "Burkina Faso": "BFA",
  "Ethiopia": "ETH",
  "Angola": "ANG",
  "Namibia": "NAM",
  "Zimbabwe": "ZIM",
  "Kenya": "KEN",
  "Equatorial Guinea": "EQG",
  "Gabon": "GAB",
  "Congo": "CGO",
  "Libya": "LBA",
  "Sudan": "SUD",
  "Malawi": "MWI",
  "Niger": "NIG",
  "Mauritania": "MTN",
  "Madagascar": "MAD",
  "Central African Republic": "CTA",
  "Togo": "TOG",
  "Sierra Leone": "SLE",
  "Liberia": "LBR",
  "Guinea-Bissau": "GNB",
  "Gambia": "GAM",

  // AFC
  "Japan": "JPN",
  "South Korea": "KOR", "Korea Republic": "KOR", "Republic of Korea": "KOR",
  "Australia": "AUS",
  "Iran": "IRN", "IR Iran": "IRN",
  "Saudi Arabia": "KSA",
  "Qatar": "QAT",
  "Iraq": "IRQ",
  "Jordan": "JOR",
  "Uzbekistan": "UZB",
  "Bahrain": "BHR",
  "United Arab Emirates": "UAE", "UAE": "UAE",
  "China": "CHN", "China PR": "CHN",
  "India": "IND",
  "Oman": "OMA",
  "Kuwait": "KUW",
  "Indonesia": "IDN",
  "Kyrgyzstan": "KGZ",
  "Palestine": "PLE",
  "Syria": "SYR",
  "Vietnam": "VIE",
  "Thailand": "THA",
  "Malaysia": "MAS",
  "Philippines": "PHI",
  "North Korea": "PRK",
  "Tajikistan": "TJK",
  "Lebanon": "LBN",
  "Myanmar": "MYA",
  "Singapore": "SIN",
  "Hong Kong": "HKG",
  "Afghanistan": "AFG",
  "Turkmenistan": "TKM",
  "Nepal": "NEP",
  "Sri Lanka": "SRI",
  "Mongolia": "MGL",
  "Maldives": "MDV",
  "Laos": "LAO",
  "Cambodia": "CAM",

  // OFC
  "New Zealand": "NZL",
  "Papua New Guinea": "PNG",
  "Fiji": "FIJ",
  "Solomon Islands": "SOL",
  "Vanuatu": "VAN",
  "Samoa": "SAM",
  "Tonga": "TGA",
  "Cook Islands": "COK",
};

export function getTeamTLA(name: string | null | undefined): string {
  if (!name) return "TBD";
  return TLA[name] ?? name.slice(0, 3).toUpperCase();
}
