const CODES: Record<string, string> = {
  // CONCACAF
  "United States": "us", "USA": "us",
  "Mexico": "mx",
  "Canada": "ca",
  "Panama": "pa",
  "Costa Rica": "cr",
  "Honduras": "hn",
  "Jamaica": "jm",
  "El Salvador": "sv",
  "Trinidad and Tobago": "tt",
  "Cuba": "cu",

  // CONMEBOL
  "Brazil": "br",
  "Argentina": "ar",
  "Colombia": "co",
  "Uruguay": "uy",
  "Ecuador": "ec",
  "Paraguay": "py",
  "Bolivia": "bo",
  "Chile": "cl",
  "Peru": "pe",
  "Venezuela": "ve",

  // UEFA
  "Germany": "de",
  "France": "fr",
  "Spain": "es",
  "Portugal": "pt",
  "England": "gb-eng",
  "Netherlands": "nl",
  "Italy": "it",
  "Belgium": "be",
  "Croatia": "hr",
  "Switzerland": "ch",
  "Serbia": "rs",
  "Turkey": "tr", "Türkiye": "tr",
  "Austria": "at",
  "Scotland": "gb-sct",
  "Czechia": "cz", "Czech Republic": "cz",
  "Slovakia": "sk",
  "Poland": "pl",
  "Hungary": "hu",
  "Denmark": "dk",
  "Wales": "gb-wls",
  "Ukraine": "ua",
  "Greece": "gr",
  "Romania": "ro",
  "Slovenia": "si",
  "Albania": "al",
  "Iceland": "is",
  "Norway": "no",
  "Sweden": "se",
  "Finland": "fi",
  "Republic of Ireland": "ie", "Ireland": "ie",
  "Northern Ireland": "gb-nir",
  "Georgia": "ge",
  "Kosovo": "xk",
  "Bosnia and Herzegovina": "ba", "Bosnia & Herzegovina": "ba", "Bosnia-Herzegovina": "ba", "Bosnia": "ba",
  "North Macedonia": "mk",
  "Bulgaria": "bg",
  "Montenegro": "me",
  "Israel": "il",
  "Armenia": "am",
  "Azerbaijan": "az",
  "Luxembourg": "lu",
  "Belarus": "by",
  "Moldova": "md",
  "Lithuania": "lt",
  "Latvia": "lv",
  "Estonia": "ee",
  "Malta": "mt",
  "Cyprus": "cy",
  "Kazakhstan": "kz",
  "Andorra": "ad",
  "Faroe Islands": "fo",
  "Gibraltar": "gi",
  "Liechtenstein": "li",
  "San Marino": "sm",

  // CAF
  "Morocco": "ma",
  "Senegal": "sn",
  "Egypt": "eg",
  "Nigeria": "ng",
  "Cameroon": "cm",
  "Ghana": "gh",
  "Ivory Coast": "ci", "Côte d'Ivoire": "ci", "Cote d'Ivoire": "ci",
  "Algeria": "dz",
  "Tunisia": "tn",
  "DR Congo": "cd", "Congo DR": "cd", "Democratic Republic of the Congo": "cd",
  "Benin": "bj",
  "Comoros": "km",
  "South Africa": "za",
  "Mali": "ml",
  "Zambia": "zm",
  "Guinea": "gn",
  "Cape Verde": "cv",
  "Cabo Verde": "cv",
  "Tanzania": "tz",
  "Uganda": "ug",
  "Mozambique": "mz",
  "Rwanda": "rw",
  "Burkina Faso": "bf",
  "Ethiopia": "et",
  "Angola": "ao",
  "Namibia": "na",
  "Zimbabwe": "zw",
  "Kenya": "ke",
  "Equatorial Guinea": "gq",
  "Gabon": "ga",
  "Congo": "cg",
  "Libya": "ly",
  "Sudan": "sd",
  "Malawi": "mw",
  "Niger": "ne",
  "Mauritania": "mr",
  "Madagascar": "mg",
  "Central African Republic": "cf",
  "Haiti": "ht",
  "Curaçao": "cw", "Curacao": "cw",
  "Togo": "tg",
  "Sierra Leone": "sl",
  "Liberia": "lr",
  "Guinea-Bissau": "gw",
  "Gambia": "gm",

  // AFC
  "Japan": "jp",
  "South Korea": "kr", "Korea Republic": "kr", "Republic of Korea": "kr",
  "Australia": "au",
  "Iran": "ir", "IR Iran": "ir",
  "Saudi Arabia": "sa",
  "Qatar": "qa",
  "Iraq": "iq",
  "Jordan": "jo",
  "Uzbekistan": "uz",
  "Bahrain": "bh",
  "United Arab Emirates": "ae", "UAE": "ae",
  "China": "cn", "China PR": "cn",
  "India": "in",
  "Oman": "om",
  "Kuwait": "kw",
  "Indonesia": "id",
  "Kyrgyzstan": "kg",
  "Palestine": "ps",
  "Syria": "sy",
  "Vietnam": "vn",
  "Thailand": "th",
  "Malaysia": "my",
  "Philippines": "ph",
  "North Korea": "kp",
  "Tajikistan": "tj",
  "Lebanon": "lb",
  "Myanmar": "mm",
  "Singapore": "sg",
  "Hong Kong": "hk",
  "Afghanistan": "af",
  "Turkmenistan": "tm",
  "Nepal": "np",
  "Sri Lanka": "lk",
  "Mongolia": "mn",
  "Maldives": "mv",
  "Laos": "la",
  "Cambodia": "kh",

  // OFC
  "New Zealand": "nz",
  "Papua New Guinea": "pg",
  "Fiji": "fj",
  "Solomon Islands": "sb",
  "Vanuatu": "vu",
  "Samoa": "ws",
  "Tonga": "to",
  "Cook Islands": "ck",
};

export function getFlagUrl(teamName: string): string | null {
  const code = CODES[teamName];
  if (!code) return null;
  return `https://flagcdn.com/w40/${code}.png`;
}
